id: 0d92507d-1646-44f8-be81-79d79c1df623
host: localhost
port_tcp: 12001
port_http: 15001
log_path: /tmp
fragment_base: /tmp/single
storage_backend: cassandra
cassandra_host: localhost
cassandra_keyspace: pilosa
supported_frames:
 - b.n
 - t.t
 - l.n
 - d
 - p.n
etcd_servers:
         - http://127.0.0.1:4001
